//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarProject.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int CarId { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_email { get; set; }
        public string Country { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
        public int Annual_Salary { get; set; }
        public int Credit_Card_Debt { get; set; }
        public int Net_Worth { get; set; }
        public int Car_Purchase_Amount { get; set; }
    }
}
